name: 14 - Use Artifact
on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/app-nest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            
            - name: Download cache Dependencies
              uses: actions/cache@v3
              id: cache
              with:
                path: 14-artifacts/node_modules
                key: deps-node-modules-${{ hashFiles('14-artifact/app-nest/yarn.lock') }}
            - name: Install dependecies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install
            - name: Unit test
              run: yarn test
            - name: Build code
              run: yarn run build
            
            - name: Upload dist files
              uses: actions/upload-artifact@v3
              with:
                name: app
                path: 14-artifacts/app-nest/dist
              
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download dist artifact
              uses: actions/download-artifact@v3
              with:
                name: app
                path: dist
            - name: Show folder struct
              run: ls -R
